version: "3.3"

services:
  app:
    container_name: "DTP__WG__API"
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: dtp__wg__api:1.0
    restart: always
    env_file: .env
    ports:
      - "8001:8000"
    volumes:
      - .:/app/
    command: python main.py
    tty: True
    depends_on:
      - psql
      - migration
  migration:
    container_name: DTP__WG__migration
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app/
    image: dtp__wg__migration:1.0
    env_file: .env
    command: bash -c "alembic stamp head && alembic revision --autogenerate -m "update" && alembic upgrade head"
  psql:
    restart: always
    container_name: "DTP__WG__PSQL"
    image: postgres:13.2-alpine
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
