"""update

Revision ID: 1df08b9cfb83
Revises: 
Create Date: 2021-08-09 10:10:55.661523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df08b9cfb83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('responsible',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shape_types',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wg_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wg_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), nullable=False),
    sa.Column('start_protocol', sa.DateTime(), nullable=False),
    sa.Column('end_protocol', sa.DateTime(), nullable=False),
    sa.Column('start_realization', sa.DateTime(), nullable=False),
    sa.Column('end_realization', sa.DateTime(), nullable=False),
    sa.Column('type_id', sa.SmallInteger(), nullable=False),
    sa.Column('status_id', sa.SmallInteger(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['responsible.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['wg_statuses.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['wg_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shapes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('color', sa.VARCHAR(length=6), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('border_color', sa.VARCHAR(length=6), nullable=False),
    sa.Column('border_width', sa.Integer(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('shape_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('work_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shape_type_id'], ['shape_types.id'], ),
    sa.ForeignKeyConstraint(['work_group_id'], ['work_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shapes')
    op.drop_table('work_groups')
    op.drop_table('wg_types')
    op.drop_table('wg_statuses')
    op.drop_table('shape_types')
    op.drop_table('responsible')
    # ### end Alembic commands ###
