"""update

Revision ID: 6ab93a38cfa2
Revises: ecbdad5c14e4
Create Date: 2021-08-09 11:13:51.699016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ab93a38cfa2'
down_revision = 'ecbdad5c14e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
