"""update

Revision ID: c02da5a4e367
Revises: 1df08b9cfb83
Create Date: 2021-08-09 10:12:08.100643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02da5a4e367'
down_revision = '1df08b9cfb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
