"""update

Revision ID: e25459a9b210
Revises: 6ab93a38cfa2
Create Date: 2021-08-09 11:23:16.160436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25459a9b210'
down_revision = '6ab93a38cfa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
