"""update

Revision ID: ecbdad5c14e4
Revises: c02da5a4e367
Create Date: 2021-08-09 10:14:00.947568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbdad5c14e4'
down_revision = 'c02da5a4e367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
