"""update

Revision ID: f1e57ae3e0b7
Revises: e25459a9b210
Create Date: 2021-08-09 12:30:02.175257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e57ae3e0b7'
down_revision = 'e25459a9b210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
